const PROBLEMS = [
  // Day 1-5: Arrays Basics
  { day: 1, topic: "Arrays", name: "Two Sum", link: "https://leetcode.com/problems/two-sum/", difficulty: "Easy" },
  { day: 1, topic: "Arrays", name: "Best Time to Buy and Sell Stock", link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", difficulty: "Easy" },
  { day: 1, topic: "Arrays", name: "Contains Duplicate", link: "https://leetcode.com/problems/contains-duplicate/", difficulty: "Easy" },
  { day: 2, topic: "Arrays", name: "Product of Array Except Self", link: "https://leetcode.com/problems/product-of-array-except-self/", difficulty: "Medium" },
  { day: 2, topic: "Arrays", name: "Maximum Subarray", link: "https://leetcode.com/problems/maximum-subarray/", difficulty: "Medium" },
  { day: 2, topic: "Arrays", name: "Maximum Product Subarray", link: "https://leetcode.com/problems/maximum-product-subarray/", difficulty: "Medium" },
  { day: 3, topic: "Arrays", name: "Find Minimum in Rotated Sorted Array", link: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/", difficulty: "Medium" },
  { day: 3, topic: "Arrays", name: "Search in Rotated Sorted Array", link: "https://leetcode.com/problems/search-in-rotated-sorted-array/", difficulty: "Medium" },
  { day: 3, topic: "Arrays", name: "3Sum", link: "https://leetcode.com/problems/3sum/", difficulty: "Medium" },
  { day: 4, topic: "Arrays", name: "Container With Most Water", link: "https://leetcode.com/problems/container-with-most-water/", difficulty: "Medium" },
  { day: 4, topic: "Arrays", name: "Move Zeroes", link: "https://leetcode.com/problems/move-zeroes/", difficulty: "Easy" },
  { day: 4, topic: "Arrays", name: "Sort Colors", link: "https://leetcode.com/problems/sort-colors/", difficulty: "Medium" },
  { day: 5, topic: "Arrays", name: "Next Permutation", link: "https://leetcode.com/problems/next-permutation/", difficulty: "Medium" },
  { day: 5, topic: "Arrays", name: "Merge Intervals", link: "https://leetcode.com/problems/merge-intervals/", difficulty: "Medium" },
  { day: 5, topic: "Arrays", name: "Set Matrix Zeroes", link: "https://leetcode.com/problems/set-matrix-zeroes/", difficulty: "Medium" },

  // Day 6-10: Arrays Advanced
  { day: 6, topic: "Arrays", name: "Spiral Matrix", link: "https://leetcode.com/problems/spiral-matrix/", difficulty: "Medium" },
  { day: 6, topic: "Arrays", name: "Rotate Image", link: "https://leetcode.com/problems/rotate-image/", difficulty: "Medium" },
  { day: 6, topic: "Arrays", name: "Word Search", link: "https://leetcode.com/problems/word-search/", difficulty: "Medium" },
  { day: 7, topic: "Arrays", name: "First Missing Positive", link: "https://leetcode.com/problems/first-missing-positive/", difficulty: "Hard" },
  { day: 7, topic: "Arrays", name: "Trapping Rain Water", link: "https://leetcode.com/problems/trapping-rain-water/", difficulty: "Hard" },
  { day: 7, topic: "Arrays", name: "Largest Rectangle in Histogram", link: "https://leetcode.com/problems/largest-rectangle-in-histogram/", difficulty: "Hard" },
  { day: 8, topic: "Arrays", name: "Subarray Sum Equals K", link: "https://leetcode.com/problems/subarray-sum-equals-k/", difficulty: "Medium" },
  { day: 8, topic: "Arrays", name: "Find All Duplicates in an Array", link: "https://leetcode.com/problems/find-all-duplicates-in-an-array/", difficulty: "Medium" },
  { day: 8, topic: "Arrays", name: "Game of Life", link: "https://leetcode.com/problems/game-of-life/", difficulty: "Medium" },
  { day: 9, topic: "Arrays", name: "Insert Interval", link: "https://leetcode.com/problems/insert-interval/", difficulty: "Medium" },
  { day: 9, topic: "Arrays", name: "Non-overlapping Intervals", link: "https://leetcode.com/problems/non-overlapping-intervals/", difficulty: "Medium" },
  { day: 9, topic: "Arrays", name: "Meeting Rooms II", link: "https://leetcode.com/problems/meeting-rooms-ii/", difficulty: "Medium" },
  { day: 10, topic: "Arrays", name: "Longest Consecutive Sequence", link: "https://leetcode.com/problems/longest-consecutive-sequence/", difficulty: "Medium" },
  { day: 10, topic: "Arrays", name: "4Sum", link: "https://leetcode.com/problems/4sum/", difficulty: "Medium" },
  { day: 10, topic: "Arrays", name: "Majority Element", link: "https://leetcode.com/problems/majority-element/", difficulty: "Easy" },

  // Day 11-18: Strings
  { day: 11, topic: "Strings", name: "Valid Anagram", link: "https://leetcode.com/problems/valid-anagram/", difficulty: "Easy" },
  { day: 11, topic: "Strings", name: "Valid Palindrome", link: "https://leetcode.com/problems/valid-palindrome/", difficulty: "Easy" },
  { day: 11, topic: "Strings", name: "Longest Substring Without Repeating Characters", link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/", difficulty: "Medium" },
  { day: 12, topic: "Strings", name: "Longest Palindromic Substring", link: "https://leetcode.com/problems/longest-palindromic-substring/", difficulty: "Medium" },
  { day: 12, topic: "Strings", name: "Group Anagrams", link: "https://leetcode.com/problems/group-anagrams/", difficulty: "Medium" },
  { day: 12, topic: "Strings", name: "Palindromic Substrings", link: "https://leetcode.com/problems/palindromic-substrings/", difficulty: "Medium" },
  { day: 13, topic: "Strings", name: "Minimum Window Substring", link: "https://leetcode.com/problems/minimum-window-substring/", difficulty: "Hard" },
  { day: 13, topic: "Strings", name: "Encode and Decode Strings", link: "https://leetcode.com/problems/encode-and-decode-strings/", difficulty: "Medium" },
  { day: 13, topic: "Strings", name: "Longest Repeating Character Replacement", link: "https://leetcode.com/problems/longest-repeating-character-replacement/", difficulty: "Medium" },
  { day: 14, topic: "Strings", name: "Valid Parentheses", link: "https://leetcode.com/problems/valid-parentheses/", difficulty: "Easy" },
  { day: 14, topic: "Strings", name: "Generate Parentheses", link: "https://leetcode.com/problems/generate-parentheses/", difficulty: "Medium" },
  { day: 14, topic: "Strings", name: "String to Integer (atoi)", link: "https://leetcode.com/problems/string-to-integer-atoi/", difficulty: "Medium" },
  { day: 15, topic: "Strings", name: "Implement strStr()", link: "https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/", difficulty: "Easy" },
  { day: 15, topic: "Strings", name: "Zigzag Conversion", link: "https://leetcode.com/problems/zigzag-conversion/", difficulty: "Medium" },
  { day: 15, topic: "Strings", name: "Regular Expression Matching", link: "https://leetcode.com/problems/regular-expression-matching/", difficulty: "Hard" },
  { day: 16, topic: "Strings", name: "Letter Combinations of a Phone Number", link: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/", difficulty: "Medium" },
  { day: 16, topic: "Strings", name: "Word Break", link: "https://leetcode.com/problems/word-break/", difficulty: "Medium" },
  { day: 16, topic: "Strings", name: "Permutation in String", link: "https://leetcode.com/problems/permutation-in-string/", difficulty: "Medium" },
  { day: 17, topic: "Strings", name: "Find All Anagrams in a String", link: "https://leetcode.com/problems/find-all-anagrams-in-a-string/", difficulty: "Medium" },
  { day: 17, topic: "Strings", name: "Longest Common Prefix", link: "https://leetcode.com/problems/longest-common-prefix/", difficulty: "Easy" },
  { day: 17, topic: "Strings", name: "Count and Say", link: "https://leetcode.com/problems/count-and-say/", difficulty: "Medium" },
  { day: 18, topic: "Strings", name: "Wildcard Matching", link: "https://leetcode.com/problems/wildcard-matching/", difficulty: "Hard" },
  { day: 18, topic: "Strings", name: "Edit Distance", link: "https://leetcode.com/problems/edit-distance/", difficulty: "Medium" },
  { day: 18, topic: "Strings", name: "Repeated DNA Sequences", link: "https://leetcode.com/problems/repeated-dna-sequences/", difficulty: "Medium" },

  // Day 19-28: Linked List
  { day: 19, topic: "Linked List", name: "Reverse Linked List", link: "https://leetcode.com/problems/reverse-linked-list/", difficulty: "Easy" },
  { day: 19, topic: "Linked List", name: "Linked List Cycle", link: "https://leetcode.com/problems/linked-list-cycle/", difficulty: "Easy" },
  { day: 19, topic: "Linked List", name: "Merge Two Sorted Lists", link: "https://leetcode.com/problems/merge-two-sorted-lists/", difficulty: "Easy" },
  { day: 20, topic: "Linked List", name: "Remove Nth Node From End of List", link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/", difficulty: "Medium" },
  { day: 20, topic: "Linked List", name: "Reorder List", link: "https://leetcode.com/problems/reorder-list/", difficulty: "Medium" },
  { day: 20, topic: "Linked List", name: "Add Two Numbers", link: "https://leetcode.com/problems/add-two-numbers/", difficulty: "Medium" },
  { day: 21, topic: "Linked List", name: "Merge k Sorted Lists", link: "https://leetcode.com/problems/merge-k-sorted-lists/", difficulty: "Hard" },
  { day: 21, topic: "Linked List", name: "Linked List Cycle II", link: "https://leetcode.com/problems/linked-list-cycle-ii/", difficulty: "Medium" },
  { day: 21, topic: "Linked List", name: "Copy List with Random Pointer", link: "https://leetcode.com/problems/copy-list-with-random-pointer/", difficulty: "Medium" },
  { day: 22, topic: "Linked List", name: "Flatten a Multilevel Doubly Linked List", link: "https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/", difficulty: "Medium" },
  { day: 22, topic: "Linked List", name: "Sort List", link: "https://leetcode.com/problems/sort-list/", difficulty: "Medium" },
  { day: 22, topic: "Linked List", name: "Intersection of Two Linked Lists", link: "https://leetcode.com/problems/intersection-of-two-linked-lists/", difficulty: "Easy" },
  { day: 23, topic: "Linked List", name: "Palindrome Linked List", link: "https://leetcode.com/problems/palindrome-linked-list/", difficulty: "Easy" },
  { day: 23, topic: "Linked List", name: "Reverse Nodes in k-Group", link: "https://leetcode.com/problems/reverse-nodes-in-k-group/", difficulty: "Hard" },
  { day: 23, topic: "Linked List", name: "Odd Even Linked List", link: "https://leetcode.com/problems/odd-even-linked-list/", difficulty: "Medium" },
  { day: 24, topic: "Linked List", name: "Swap Nodes in Pairs", link: "https://leetcode.com/problems/swap-nodes-in-pairs/", difficulty: "Medium" },
  { day: 24, topic: "Linked List", name: "Remove Duplicates from Sorted List II", link: "https://leetcode.com/problems/remove-duplicates-from-sorted-list-ii/", difficulty: "Medium" },
  { day: 24, topic: "Linked List", name: "Rotate List", link: "https://leetcode.com/problems/rotate-list/", difficulty: "Medium" },
  { day: 25, topic: "Linked List", name: "LRU Cache", link: "https://leetcode.com/problems/lru-cache/", difficulty: "Medium" },
  { day: 25, topic: "Linked List", name: "Design Linked List", link: "https://leetcode.com/problems/design-linked-list/", difficulty: "Medium" },
  { day: 25, topic: "Linked List", name: "Partition List", link: "https://leetcode.com/problems/partition-list/", difficulty: "Medium" },

  // Day 26-30: Stacks & Queues
  { day: 26, topic: "Stack & Queue", name: "Min Stack", link: "https://leetcode.com/problems/min-stack/", difficulty: "Medium" },
  { day: 26, topic: "Stack & Queue", name: "Implement Queue using Stacks", link: "https://leetcode.com/problems/implement-queue-using-stacks/", difficulty: "Easy" },
  { day: 26, topic: "Stack & Queue", name: "Evaluate Reverse Polish Notation", link: "https://leetcode.com/problems/evaluate-reverse-polish-notation/", difficulty: "Medium" },
  { day: 27, topic: "Stack & Queue", name: "Daily Temperatures", link: "https://leetcode.com/problems/daily-temperatures/", difficulty: "Medium" },
  { day: 27, topic: "Stack & Queue", name: "Next Greater Element I", link: "https://leetcode.com/problems/next-greater-element-i/", difficulty: "Easy" },
  { day: 27, topic: "Stack & Queue", name: "Sliding Window Maximum", link: "https://leetcode.com/problems/sliding-window-maximum/", difficulty: "Hard" },
  { day: 28, topic: "Stack & Queue", name: "Basic Calculator II", link: "https://leetcode.com/problems/basic-calculator-ii/", difficulty: "Medium" },
  { day: 28, topic: "Stack & Queue", name: "Decode String", link: "https://leetcode.com/problems/decode-string/", difficulty: "Medium" },
  { day: 28, topic: "Stack & Queue", name: "Asteroid Collision", link: "https://leetcode.com/problems/asteroid-collision/", difficulty: "Medium" },
  { day: 29, topic: "Stack & Queue", name: "Online Stock Span", link: "https://leetcode.com/problems/online-stock-span/", difficulty: "Medium" },
  { day: 29, topic: "Stack & Queue", name: "Simplify Path", link: "https://leetcode.com/problems/simplify-path/", difficulty: "Medium" },
  { day: 29, topic: "Stack & Queue", name: "Car Fleet", link: "https://leetcode.com/problems/car-fleet/", difficulty: "Medium" },
  { day: 30, topic: "Stack & Queue", name: "Longest Valid Parentheses", link: "https://leetcode.com/problems/longest-valid-parentheses/", difficulty: "Hard" },
  { day: 30, topic: "Stack & Queue", name: "Remove K Digits", link: "https://leetcode.com/problems/remove-k-digits/", difficulty: "Medium" },
  { day: 30, topic: "Stack & Queue", name: "Task Scheduler", link: "https://leetcode.com/problems/task-scheduler/", difficulty: "Medium" },

  // Day 31-40: Binary Trees
  { day: 31, topic: "Binary Tree", name: "Maximum Depth of Binary Tree", link: "https://leetcode.com/problems/maximum-depth-of-binary-tree/", difficulty: "Easy" },
  { day: 31, topic: "Binary Tree", name: "Invert Binary Tree", link: "https://leetcode.com/problems/invert-binary-tree/", difficulty: "Easy" },
  { day: 31, topic: "Binary Tree", name: "Same Tree", link: "https://leetcode.com/problems/same-tree/", difficulty: "Easy" },
  { day: 32, topic: "Binary Tree", name: "Binary Tree Level Order Traversal", link: "https://leetcode.com/problems/binary-tree-level-order-traversal/", difficulty: "Medium" },
  { day: 32, topic: "Binary Tree", name: "Subtree of Another Tree", link: "https://leetcode.com/problems/subtree-of-another-tree/", difficulty: "Easy" },
  { day: 32, topic: "Binary Tree", name: "Construct Binary Tree from Preorder and Inorder", link: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/", difficulty: "Medium" },
  { day: 33, topic: "Binary Tree", name: "Validate Binary Search Tree", link: "https://leetcode.com/problems/validate-binary-search-tree/", difficulty: "Medium" },
  { day: 33, topic: "Binary Tree", name: "Kth Smallest Element in a BST", link: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/", difficulty: "Medium" },
  { day: 33, topic: "Binary Tree", name: "Lowest Common Ancestor of a BST", link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", difficulty: "Medium" },
  { day: 34, topic: "Binary Tree", name: "Binary Tree Right Side View", link: "https://leetcode.com/problems/binary-tree-right-side-view/", difficulty: "Medium" },
  { day: 34, topic: "Binary Tree", name: "Count Good Nodes in Binary Tree", link: "https://leetcode.com/problems/count-good-nodes-in-binary-tree/", difficulty: "Medium" },
  { day: 34, topic: "Binary Tree", name: "Lowest Common Ancestor of a Binary Tree", link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/", difficulty: "Medium" },
  { day: 35, topic: "Binary Tree", name: "Binary Tree Zigzag Level Order Traversal", link: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/", difficulty: "Medium" },
  { day: 35, topic: "Binary Tree", name: "Path Sum", link: "https://leetcode.com/problems/path-sum/", difficulty: "Easy" },
  { day: 35, topic: "Binary Tree", name: "Path Sum III", link: "https://leetcode.com/problems/path-sum-iii/", difficulty: "Medium" },
  { day: 36, topic: "Binary Tree", name: "Diameter of Binary Tree", link: "https://leetcode.com/problems/diameter-of-binary-tree/", difficulty: "Easy" },
  { day: 36, topic: "Binary Tree", name: "Balanced Binary Tree", link: "https://leetcode.com/problems/balanced-binary-tree/", difficulty: "Easy" },
  { day: 36, topic: "Binary Tree", name: "Symmetric Tree", link: "https://leetcode.com/problems/symmetric-tree/", difficulty: "Easy" },
  { day: 37, topic: "Binary Tree", name: "Serialize and Deserialize Binary Tree", link: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/", difficulty: "Hard" },
  { day: 37, topic: "Binary Tree", name: "Binary Tree Maximum Path Sum", link: "https://leetcode.com/problems/binary-tree-maximum-path-sum/", difficulty: "Hard" },
  { day: 37, topic: "Binary Tree", name: "Flatten Binary Tree to Linked List", link: "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/", difficulty: "Medium" },
  { day: 38, topic: "Binary Tree", name: "Populating Next Right Pointers", link: "https://leetcode.com/problems/populating-next-right-pointers-in-each-node/", difficulty: "Medium" },
  { day: 38, topic: "Binary Tree", name: "Sum Root to Leaf Numbers", link: "https://leetcode.com/problems/sum-root-to-leaf-numbers/", difficulty: "Medium" },
  { day: 38, topic: "Binary Tree", name: "Binary Search Tree Iterator", link: "https://leetcode.com/problems/binary-search-tree-iterator/", difficulty: "Medium" },
  { day: 39, topic: "Binary Tree", name: "Recover Binary Search Tree", link: "https://leetcode.com/problems/recover-binary-search-tree/", difficulty: "Medium" },
  { day: 39, topic: "Binary Tree", name: "Convert Sorted Array to BST", link: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/", difficulty: "Easy" },
  { day: 39, topic: "Binary Tree", name: "Delete Node in a BST", link: "https://leetcode.com/problems/delete-node-in-a-bst/", difficulty: "Medium" },
  { day: 40, topic: "Binary Tree", name: "All Nodes Distance K in Binary Tree", link: "https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/", difficulty: "Medium" },
  { day: 40, topic: "Binary Tree", name: "Vertical Order Traversal", link: "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/", difficulty: "Hard" },
  { day: 40, topic: "Binary Tree", name: "House Robber III", link: "https://leetcode.com/problems/house-robber-iii/", difficulty: "Medium" },

  // Day 41-48: Heap / Priority Queue
  { day: 41, topic: "Heap", name: "Kth Largest Element in an Array", link: "https://leetcode.com/problems/kth-largest-element-in-an-array/", difficulty: "Medium" },
  { day: 41, topic: "Heap", name: "Top K Frequent Elements", link: "https://leetcode.com/problems/top-k-frequent-elements/", difficulty: "Medium" },
  { day: 41, topic: "Heap", name: "Find Median from Data Stream", link: "https://leetcode.com/problems/find-median-from-data-stream/", difficulty: "Hard" },
  { day: 42, topic: "Heap", name: "K Closest Points to Origin", link: "https://leetcode.com/problems/k-closest-points-to-origin/", difficulty: "Medium" },
  { day: 42, topic: "Heap", name: "Sort Characters By Frequency", link: "https://leetcode.com/problems/sort-characters-by-frequency/", difficulty: "Medium" },
  { day: 42, topic: "Heap", name: "Reorganize String", link: "https://leetcode.com/problems/reorganize-string/", difficulty: "Medium" },
  { day: 43, topic: "Heap", name: "Kth Smallest Element in Sorted Matrix", link: "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/", difficulty: "Medium" },
  { day: 43, topic: "Heap", name: "Find K Pairs with Smallest Sums", link: "https://leetcode.com/problems/find-k-pairs-with-smallest-sums/", difficulty: "Medium" },
  { day: 43, topic: "Heap", name: "Ugly Number II", link: "https://leetcode.com/problems/ugly-number-ii/", difficulty: "Medium" },

  // Day 44-48: Hashing
  { day: 44, topic: "Hash Map", name: "Design HashMap", link: "https://leetcode.com/problems/design-hashmap/", difficulty: "Easy" },
  { day: 44, topic: "Hash Map", name: "First Unique Character in a String", link: "https://leetcode.com/problems/first-unique-character-in-a-string/", difficulty: "Easy" },
  { day: 44, topic: "Hash Map", name: "Isomorphic Strings", link: "https://leetcode.com/problems/isomorphic-strings/", difficulty: "Easy" },
  { day: 45, topic: "Hash Map", name: "Happy Number", link: "https://leetcode.com/problems/happy-number/", difficulty: "Easy" },
  { day: 45, topic: "Hash Map", name: "Word Pattern", link: "https://leetcode.com/problems/word-pattern/", difficulty: "Easy" },
  { day: 45, topic: "Hash Map", name: "Contiguous Array", link: "https://leetcode.com/problems/contiguous-array/", difficulty: "Medium" },
  { day: 46, topic: "Hash Map", name: "Longest Palindrome", link: "https://leetcode.com/problems/longest-palindrome/", difficulty: "Easy" },
  { day: 46, topic: "Hash Map", name: "Top K Frequent Words", link: "https://leetcode.com/problems/top-k-frequent-words/", difficulty: "Medium" },
  { day: 46, topic: "Hash Map", name: "Brick Wall", link: "https://leetcode.com/problems/brick-wall/", difficulty: "Medium" },
  { day: 47, topic: "Hash Map", name: "Longest Substring with At Most K Distinct Characters", link: "https://leetcode.com/problems/longest-substring-with-at-most-k-distinct-characters/", difficulty: "Medium" },
  { day: 47, topic: "Hash Map", name: "Insert Delete GetRandom O(1)", link: "https://leetcode.com/problems/insert-delete-getrandom-o1/", difficulty: "Medium" },
  { day: 47, topic: "Hash Map", name: "Minimum Window Substring", link: "https://leetcode.com/problems/minimum-window-substring/", difficulty: "Hard" },
  { day: 48, topic: "Hash Map", name: "LFU Cache", link: "https://leetcode.com/problems/lfu-cache/", difficulty: "Hard" },
  { day: 48, topic: "Hash Map", name: "Snapshot Array", link: "https://leetcode.com/problems/snapshot-array/", difficulty: "Medium" },
  { day: 48, topic: "Hash Map", name: "Time Based Key-Value Store", link: "https://leetcode.com/problems/time-based-key-value-store/", difficulty: "Medium" },

  // Day 49-58: Graphs
  { day: 49, topic: "Graph", name: "Number of Islands", link: "https://leetcode.com/problems/number-of-islands/", difficulty: "Medium" },
  { day: 49, topic: "Graph", name: "Clone Graph", link: "https://leetcode.com/problems/clone-graph/", difficulty: "Medium" },
  { day: 49, topic: "Graph", name: "Pacific Atlantic Water Flow", link: "https://leetcode.com/problems/pacific-atlantic-water-flow/", difficulty: "Medium" },
  { day: 50, topic: "Graph", name: "Course Schedule", link: "https://leetcode.com/problems/course-schedule/", difficulty: "Medium" },
  { day: 50, topic: "Graph", name: "Course Schedule II", link: "https://leetcode.com/problems/course-schedule-ii/", difficulty: "Medium" },
  { day: 50, topic: "Graph", name: "Number of Connected Components", link: "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/", difficulty: "Medium" },
  { day: 51, topic: "Graph", name: "Graph Valid Tree", link: "https://leetcode.com/problems/graph-valid-tree/", difficulty: "Medium" },
  { day: 51, topic: "Graph", name: "Redundant Connection", link: "https://leetcode.com/problems/redundant-connection/", difficulty: "Medium" },
  { day: 51, topic: "Graph", name: "Surrounded Regions", link: "https://leetcode.com/problems/surrounded-regions/", difficulty: "Medium" },
  { day: 52, topic: "Graph", name: "Rotting Oranges", link: "https://leetcode.com/problems/rotting-oranges/", difficulty: "Medium" },
  { day: 52, topic: "Graph", name: "Walls and Gates", link: "https://leetcode.com/problems/walls-and-gates/", difficulty: "Medium" },
  { day: 52, topic: "Graph", name: "01 Matrix", link: "https://leetcode.com/problems/01-matrix/", difficulty: "Medium" },
  { day: 53, topic: "Graph", name: "Word Ladder", link: "https://leetcode.com/problems/word-ladder/", difficulty: "Hard" },
  { day: 53, topic: "Graph", name: "Alien Dictionary", link: "https://leetcode.com/problems/alien-dictionary/", difficulty: "Hard" },
  { day: 53, topic: "Graph", name: "Shortest Path in Binary Matrix", link: "https://leetcode.com/problems/shortest-path-in-binary-matrix/", difficulty: "Medium" },
  { day: 54, topic: "Graph", name: "Network Delay Time", link: "https://leetcode.com/problems/network-delay-time/", difficulty: "Medium" },
  { day: 54, topic: "Graph", name: "Cheapest Flights Within K Stops", link: "https://leetcode.com/problems/cheapest-flights-within-k-stops/", difficulty: "Medium" },
  { day: 54, topic: "Graph", name: "Swim in Rising Water", link: "https://leetcode.com/problems/swim-in-rising-water/", difficulty: "Hard" },
  { day: 55, topic: "Graph", name: "Accounts Merge", link: "https://leetcode.com/problems/accounts-merge/", difficulty: "Medium" },
  { day: 55, topic: "Graph", name: "Min Cost to Connect All Points", link: "https://leetcode.com/problems/min-cost-to-connect-all-points/", difficulty: "Medium" },
  { day: 55, topic: "Graph", name: "Is Graph Bipartite?", link: "https://leetcode.com/problems/is-graph-bipartite/", difficulty: "Medium" },
  { day: 56, topic: "Graph", name: "Critical Connections in a Network", link: "https://leetcode.com/problems/critical-connections-in-a-network/", difficulty: "Hard" },
  { day: 56, topic: "Graph", name: "Evaluate Division", link: "https://leetcode.com/problems/evaluate-division/", difficulty: "Medium" },
  { day: 56, topic: "Graph", name: "Snakes and Ladders", link: "https://leetcode.com/problems/snakes-and-ladders/", difficulty: "Medium" },
  { day: 57, topic: "Graph", name: "Minimum Height Trees", link: "https://leetcode.com/problems/minimum-height-trees/", difficulty: "Medium" },
  { day: 57, topic: "Graph", name: "Reconstruct Itinerary", link: "https://leetcode.com/problems/reconstruct-itinerary/", difficulty: "Hard" },
  { day: 57, topic: "Graph", name: "All Paths From Source to Target", link: "https://leetcode.com/problems/all-paths-from-source-to-target/", difficulty: "Medium" },
  { day: 58, topic: "Graph", name: "Longest Increasing Path in a Matrix", link: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/", difficulty: "Hard" },
  { day: 58, topic: "Graph", name: "Word Search II", link: "https://leetcode.com/problems/word-search-ii/", difficulty: "Hard" },
  { day: 58, topic: "Graph", name: "Open the Lock", link: "https://leetcode.com/problems/open-the-lock/", difficulty: "Medium" },

  // Day 59-70: Dynamic Programming
  { day: 59, topic: "Dynamic Programming", name: "Climbing Stairs", link: "https://leetcode.com/problems/climbing-stairs/", difficulty: "Easy" },
  { day: 59, topic: "Dynamic Programming", name: "House Robber", link: "https://leetcode.com/problems/house-robber/", difficulty: "Medium" },
  { day: 59, topic: "Dynamic Programming", name: "House Robber II", link: "https://leetcode.com/problems/house-robber-ii/", difficulty: "Medium" },
  { day: 60, topic: "Dynamic Programming", name: "Coin Change", link: "https://leetcode.com/problems/coin-change/", difficulty: "Medium" },
  { day: 60, topic: "Dynamic Programming", name: "Coin Change II", link: "https://leetcode.com/problems/coin-change-ii/", difficulty: "Medium" },
  { day: 60, topic: "Dynamic Programming", name: "Longest Increasing Subsequence", link: "https://leetcode.com/problems/longest-increasing-subsequence/", difficulty: "Medium" },
  { day: 61, topic: "Dynamic Programming", name: "Longest Common Subsequence", link: "https://leetcode.com/problems/longest-common-subsequence/", difficulty: "Medium" },
  { day: 61, topic: "Dynamic Programming", name: "Word Break", link: "https://leetcode.com/problems/word-break/", difficulty: "Medium" },
  { day: 61, topic: "Dynamic Programming", name: "Combination Sum IV", link: "https://leetcode.com/problems/combination-sum-iv/", difficulty: "Medium" },
  { day: 62, topic: "Dynamic Programming", name: "Decode Ways", link: "https://leetcode.com/problems/decode-ways/", difficulty: "Medium" },
  { day: 62, topic: "Dynamic Programming", name: "Unique Paths", link: "https://leetcode.com/problems/unique-paths/", difficulty: "Medium" },
  { day: 62, topic: "Dynamic Programming", name: "Jump Game", link: "https://leetcode.com/problems/jump-game/", difficulty: "Medium" },
  { day: 63, topic: "Dynamic Programming", name: "Jump Game II", link: "https://leetcode.com/problems/jump-game-ii/", difficulty: "Medium" },
  { day: 63, topic: "Dynamic Programming", name: "Partition Equal Subset Sum", link: "https://leetcode.com/problems/partition-equal-subset-sum/", difficulty: "Medium" },
  { day: 63, topic: "Dynamic Programming", name: "Target Sum", link: "https://leetcode.com/problems/target-sum/", difficulty: "Medium" },
  { day: 64, topic: "Dynamic Programming", name: "0/1 Knapsack (Partition Equal Subset)", link: "https://leetcode.com/problems/partition-equal-subset-sum/", difficulty: "Medium" },
  { day: 64, topic: "Dynamic Programming", name: "Palindrome Partitioning II", link: "https://leetcode.com/problems/palindrome-partitioning-ii/", difficulty: "Hard" },
  { day: 64, topic: "Dynamic Programming", name: "Interleaving String", link: "https://leetcode.com/problems/interleaving-string/", difficulty: "Medium" },
  { day: 65, topic: "Dynamic Programming", name: "Longest Palindromic Subsequence", link: "https://leetcode.com/problems/longest-palindromic-subsequence/", difficulty: "Medium" },
  { day: 65, topic: "Dynamic Programming", name: "Maximum Length of Repeated Subarray", link: "https://leetcode.com/problems/maximum-length-of-repeated-subarray/", difficulty: "Medium" },
  { day: 65, topic: "Dynamic Programming", name: "Distinct Subsequences", link: "https://leetcode.com/problems/distinct-subsequences/", difficulty: "Hard" },
  { day: 66, topic: "Dynamic Programming", name: "Best Time to Buy and Sell Stock with Cooldown", link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/", difficulty: "Medium" },
  { day: 66, topic: "Dynamic Programming", name: "Best Time to Buy and Sell Stock IV", link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/", difficulty: "Hard" },
  { day: 66, topic: "Dynamic Programming", name: "Perfect Squares", link: "https://leetcode.com/problems/perfect-squares/", difficulty: "Medium" },
  { day: 67, topic: "Dynamic Programming", name: "Maximal Square", link: "https://leetcode.com/problems/maximal-square/", difficulty: "Medium" },
  { day: 67, topic: "Dynamic Programming", name: "Minimum Path Sum", link: "https://leetcode.com/problems/minimum-path-sum/", difficulty: "Medium" },
  { day: 67, topic: "Dynamic Programming", name: "Triangle", link: "https://leetcode.com/problems/triangle/", difficulty: "Medium" },
  { day: 68, topic: "Dynamic Programming", name: "Burst Balloons", link: "https://leetcode.com/problems/burst-balloons/", difficulty: "Hard" },
  { day: 68, topic: "Dynamic Programming", name: "Matrix Chain Multiplication (Minimum Cost Tree From Leaf Values)", link: "https://leetcode.com/problems/minimum-cost-tree-from-leaf-values/", difficulty: "Medium" },
  { day: 68, topic: "Dynamic Programming", name: "Stone Game", link: "https://leetcode.com/problems/stone-game/", difficulty: "Medium" },
  { day: 69, topic: "Dynamic Programming", name: "Longest String Chain", link: "https://leetcode.com/problems/longest-string-chain/", difficulty: "Medium" },
  { day: 69, topic: "Dynamic Programming", name: "Number of Longest Increasing Subsequence", link: "https://leetcode.com/problems/number-of-longest-increasing-subsequence/", difficulty: "Medium" },
  { day: 69, topic: "Dynamic Programming", name: "Russian Doll Envelopes", link: "https://leetcode.com/problems/russian-doll-envelopes/", difficulty: "Hard" },
  { day: 70, topic: "Dynamic Programming", name: "Minimum Cost to Cut a Stick", link: "https://leetcode.com/problems/minimum-cost-to-cut-a-stick/", difficulty: "Hard" },
  { day: 70, topic: "Dynamic Programming", name: "Scramble String", link: "https://leetcode.com/problems/scramble-string/", difficulty: "Hard" },
  { day: 70, topic: "Dynamic Programming", name: "Cherry Pickup II", link: "https://leetcode.com/problems/cherry-pickup-ii/", difficulty: "Hard" },

  // Day 71-78: Binary Search
  { day: 71, topic: "Binary Search", name: "Binary Search", link: "https://leetcode.com/problems/binary-search/", difficulty: "Easy" },
  { day: 71, topic: "Binary Search", name: "Search a 2D Matrix", link: "https://leetcode.com/problems/search-a-2d-matrix/", difficulty: "Medium" },
  { day: 71, topic: "Binary Search", name: "Koko Eating Bananas", link: "https://leetcode.com/problems/koko-eating-bananas/", difficulty: "Medium" },
  { day: 72, topic: "Binary Search", name: "Find Peak Element", link: "https://leetcode.com/problems/find-peak-element/", difficulty: "Medium" },
  { day: 72, topic: "Binary Search", name: "Search in Rotated Sorted Array II", link: "https://leetcode.com/problems/search-in-rotated-sorted-array-ii/", difficulty: "Medium" },
  { day: 72, topic: "Binary Search", name: "Find First and Last Position", link: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/", difficulty: "Medium" },
  { day: 73, topic: "Binary Search", name: "Capacity To Ship Packages Within D Days", link: "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/", difficulty: "Medium" },
  { day: 73, topic: "Binary Search", name: "Split Array Largest Sum", link: "https://leetcode.com/problems/split-array-largest-sum/", difficulty: "Hard" },
  { day: 73, topic: "Binary Search", name: "Median of Two Sorted Arrays", link: "https://leetcode.com/problems/median-of-two-sorted-arrays/", difficulty: "Hard" },
  { day: 74, topic: "Binary Search", name: "Aggressive Cows (Magnetic Force Between Two Balls)", link: "https://leetcode.com/problems/magnetic-force-between-two-balls/", difficulty: "Medium" },
  { day: 74, topic: "Binary Search", name: "Minimum Number of Days to Make m Bouquets", link: "https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/", difficulty: "Medium" },
  { day: 74, topic: "Binary Search", name: "Allocate Books (Split Array Largest Sum)", link: "https://leetcode.com/problems/split-array-largest-sum/", difficulty: "Hard" },
  { day: 75, topic: "Binary Search", name: "Find the Duplicate Number", link: "https://leetcode.com/problems/find-the-duplicate-number/", difficulty: "Medium" },
  { day: 75, topic: "Binary Search", name: "Single Element in a Sorted Array", link: "https://leetcode.com/problems/single-element-in-a-sorted-array/", difficulty: "Medium" },
  { day: 75, topic: "Binary Search", name: "Search a 2D Matrix II", link: "https://leetcode.com/problems/search-a-2d-matrix-ii/", difficulty: "Medium" },

  // Day 76-80: Greedy
  { day: 76, topic: "Greedy", name: "Jump Game", link: "https://leetcode.com/problems/jump-game/", difficulty: "Medium" },
  { day: 76, topic: "Greedy", name: "Gas Station", link: "https://leetcode.com/problems/gas-station/", difficulty: "Medium" },
  { day: 76, topic: "Greedy", name: "Hand of Straights", link: "https://leetcode.com/problems/hand-of-straights/", difficulty: "Medium" },
  { day: 77, topic: "Greedy", name: "Merge Triplets to Form Target", link: "https://leetcode.com/problems/merge-triplets-to-form-target-triplet/", difficulty: "Medium" },
  { day: 77, topic: "Greedy", name: "Partition Labels", link: "https://leetcode.com/problems/partition-labels/", difficulty: "Medium" },
  { day: 77, topic: "Greedy", name: "Valid Parenthesis String", link: "https://leetcode.com/problems/valid-parenthesis-string/", difficulty: "Medium" },
  { day: 78, topic: "Greedy", name: "Maximum Subarray", link: "https://leetcode.com/problems/maximum-subarray/", difficulty: "Medium" },
  { day: 78, topic: "Greedy", name: "Minimum Number of Arrows to Burst Balloons", link: "https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/", difficulty: "Medium" },
  { day: 78, topic: "Greedy", name: "Queue Reconstruction by Height", link: "https://leetcode.com/problems/queue-reconstruction-by-height/", difficulty: "Medium" },
  { day: 79, topic: "Greedy", name: "Non-overlapping Intervals", link: "https://leetcode.com/problems/non-overlapping-intervals/", difficulty: "Medium" },
  { day: 79, topic: "Greedy", name: "Candy", link: "https://leetcode.com/problems/candy/", difficulty: "Hard" },
  { day: 79, topic: "Greedy", name: "Minimum Platforms (Meeting Rooms II)", link: "https://leetcode.com/problems/meeting-rooms-ii/", difficulty: "Medium" },
  { day: 80, topic: "Greedy", name: "Job Sequencing (Course Schedule III)", link: "https://leetcode.com/problems/course-schedule-iii/", difficulty: "Hard" },
  { day: 80, topic: "Greedy", name: "Lemonade Change", link: "https://leetcode.com/problems/lemonade-change/", difficulty: "Easy" },
  { day: 80, topic: "Greedy", name: "Boats to Save People", link: "https://leetcode.com/problems/boats-to-save-people/", difficulty: "Medium" },

  // Day 81-86: Backtracking
  { day: 81, topic: "Backtracking", name: "Subsets", link: "https://leetcode.com/problems/subsets/", difficulty: "Medium" },
  { day: 81, topic: "Backtracking", name: "Subsets II", link: "https://leetcode.com/problems/subsets-ii/", difficulty: "Medium" },
  { day: 81, topic: "Backtracking", name: "Permutations", link: "https://leetcode.com/problems/permutations/", difficulty: "Medium" },
  { day: 82, topic: "Backtracking", name: "Permutations II", link: "https://leetcode.com/problems/permutations-ii/", difficulty: "Medium" },
  { day: 82, topic: "Backtracking", name: "Combination Sum", link: "https://leetcode.com/problems/combination-sum/", difficulty: "Medium" },
  { day: 82, topic: "Backtracking", name: "Combination Sum II", link: "https://leetcode.com/problems/combination-sum-ii/", difficulty: "Medium" },
  { day: 83, topic: "Backtracking", name: "Palindrome Partitioning", link: "https://leetcode.com/problems/palindrome-partitioning/", difficulty: "Medium" },
  { day: 83, topic: "Backtracking", name: "N-Queens", link: "https://leetcode.com/problems/n-queens/", difficulty: "Hard" },
  { day: 83, topic: "Backtracking", name: "Sudoku Solver", link: "https://leetcode.com/problems/sudoku-solver/", difficulty: "Hard" },
  { day: 84, topic: "Backtracking", name: "Word Search", link: "https://leetcode.com/problems/word-search/", difficulty: "Medium" },
  { day: 84, topic: "Backtracking", name: "Restore IP Addresses", link: "https://leetcode.com/problems/restore-ip-addresses/", difficulty: "Medium" },
  { day: 84, topic: "Backtracking", name: "Letter Combinations of a Phone Number", link: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/", difficulty: "Medium" },
  { day: 85, topic: "Backtracking", name: "Combinations", link: "https://leetcode.com/problems/combinations/", difficulty: "Medium" },
  { day: 85, topic: "Backtracking", name: "Generate Parentheses", link: "https://leetcode.com/problems/generate-parentheses/", difficulty: "Medium" },
  { day: 85, topic: "Backtracking", name: "Expression Add Operators", link: "https://leetcode.com/problems/expression-add-operators/", difficulty: "Hard" },
  { day: 86, topic: "Backtracking", name: "Word Break II", link: "https://leetcode.com/problems/word-break-ii/", difficulty: "Hard" },
  { day: 86, topic: "Backtracking", name: "Rat in a Maze (Unique Paths III)", link: "https://leetcode.com/problems/unique-paths-iii/", difficulty: "Hard" },
  { day: 86, topic: "Backtracking", name: "Beautiful Arrangement", link: "https://leetcode.com/problems/beautiful-arrangement/", difficulty: "Medium" },

  // Day 87-92: Tries & Advanced Strings
  { day: 87, topic: "Trie", name: "Implement Trie (Prefix Tree)", link: "https://leetcode.com/problems/implement-trie-prefix-tree/", difficulty: "Medium" },
  { day: 87, topic: "Trie", name: "Design Add and Search Words", link: "https://leetcode.com/problems/design-add-and-search-words-data-structure/", difficulty: "Medium" },
  { day: 87, topic: "Trie", name: "Word Search II", link: "https://leetcode.com/problems/word-search-ii/", difficulty: "Hard" },
  { day: 88, topic: "Trie", name: "Longest Word in Dictionary", link: "https://leetcode.com/problems/longest-word-in-dictionary/", difficulty: "Medium" },
  { day: 88, topic: "Trie", name: "Replace Words", link: "https://leetcode.com/problems/replace-words/", difficulty: "Medium" },
  { day: 88, topic: "Trie", name: "Maximum XOR of Two Numbers in an Array", link: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/", difficulty: "Medium" },

  // Day 89-92: Two Pointers / Sliding Window
  { day: 89, topic: "Two Pointers", name: "Valid Palindrome II", link: "https://leetcode.com/problems/valid-palindrome-ii/", difficulty: "Easy" },
  { day: 89, topic: "Two Pointers", name: "3Sum Closest", link: "https://leetcode.com/problems/3sum-closest/", difficulty: "Medium" },
  { day: 89, topic: "Two Pointers", name: "Trapping Rain Water", link: "https://leetcode.com/problems/trapping-rain-water/", difficulty: "Hard" },
  { day: 90, topic: "Sliding Window", name: "Minimum Size Subarray Sum", link: "https://leetcode.com/problems/minimum-size-subarray-sum/", difficulty: "Medium" },
  { day: 90, topic: "Sliding Window", name: "Longest Repeating Character Replacement", link: "https://leetcode.com/problems/longest-repeating-character-replacement/", difficulty: "Medium" },
  { day: 90, topic: "Sliding Window", name: "Fruit Into Baskets", link: "https://leetcode.com/problems/fruit-into-baskets/", difficulty: "Medium" },
  { day: 91, topic: "Sliding Window", name: "Sliding Window Maximum", link: "https://leetcode.com/problems/sliding-window-maximum/", difficulty: "Hard" },
  { day: 91, topic: "Sliding Window", name: "Minimum Window Substring", link: "https://leetcode.com/problems/minimum-window-substring/", difficulty: "Hard" },
  { day: 91, topic: "Sliding Window", name: "Subarrays with K Different Integers", link: "https://leetcode.com/problems/subarrays-with-k-different-integers/", difficulty: "Hard" },
  { day: 92, topic: "Two Pointers", name: "Sort Colors", link: "https://leetcode.com/problems/sort-colors/", difficulty: "Medium" },
  { day: 92, topic: "Two Pointers", name: "4Sum", link: "https://leetcode.com/problems/4sum/", difficulty: "Medium" },
  { day: 92, topic: "Two Pointers", name: "Remove Duplicates from Sorted Array II", link: "https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii/", difficulty: "Medium" },

  // Day 93-98: Bit Manipulation & Math
  { day: 93, topic: "Bit Manipulation", name: "Single Number", link: "https://leetcode.com/problems/single-number/", difficulty: "Easy" },
  { day: 93, topic: "Bit Manipulation", name: "Number of 1 Bits", link: "https://leetcode.com/problems/number-of-1-bits/", difficulty: "Easy" },
  { day: 93, topic: "Bit Manipulation", name: "Counting Bits", link: "https://leetcode.com/problems/counting-bits/", difficulty: "Easy" },
  { day: 94, topic: "Bit Manipulation", name: "Reverse Bits", link: "https://leetcode.com/problems/reverse-bits/", difficulty: "Easy" },
  { day: 94, topic: "Bit Manipulation", name: "Missing Number", link: "https://leetcode.com/problems/missing-number/", difficulty: "Easy" },
  { day: 94, topic: "Bit Manipulation", name: "Sum of Two Integers", link: "https://leetcode.com/problems/sum-of-two-integers/", difficulty: "Medium" },
  { day: 95, topic: "Bit Manipulation", name: "Single Number II", link: "https://leetcode.com/problems/single-number-ii/", difficulty: "Medium" },
  { day: 95, topic: "Bit Manipulation", name: "Bitwise AND of Numbers Range", link: "https://leetcode.com/problems/bitwise-and-of-numbers-range/", difficulty: "Medium" },
  { day: 95, topic: "Bit Manipulation", name: "Power of Two", link: "https://leetcode.com/problems/power-of-two/", difficulty: "Easy" },
  { day: 96, topic: "Math", name: "Pow(x, n)", link: "https://leetcode.com/problems/powx-n/", difficulty: "Medium" },
  { day: 96, topic: "Math", name: "Sqrt(x)", link: "https://leetcode.com/problems/sqrtx/", difficulty: "Easy" },
  { day: 96, topic: "Math", name: "Multiply Strings", link: "https://leetcode.com/problems/multiply-strings/", difficulty: "Medium" },
  { day: 97, topic: "Math", name: "Happy Number", link: "https://leetcode.com/problems/happy-number/", difficulty: "Easy" },
  { day: 97, topic: "Math", name: "Plus One", link: "https://leetcode.com/problems/plus-one/", difficulty: "Easy" },
  { day: 97, topic: "Math", name: "Rotate Function", link: "https://leetcode.com/problems/rotate-function/", difficulty: "Medium" },
  { day: 98, topic: "Math", name: "Count Primes", link: "https://leetcode.com/problems/count-primes/", difficulty: "Medium" },
  { day: 98, topic: "Math", name: "Factorial Trailing Zeroes", link: "https://leetcode.com/problems/factorial-trailing-zeroes/", difficulty: "Medium" },
  { day: 98, topic: "Math", name: "Excel Sheet Column Number", link: "https://leetcode.com/problems/excel-sheet-column-number/", difficulty: "Easy" },

  // Day 99-104: Design & Advanced
  { day: 99, topic: "Design", name: "LRU Cache", link: "https://leetcode.com/problems/lru-cache/", difficulty: "Medium" },
  { day: 99, topic: "Design", name: "LFU Cache", link: "https://leetcode.com/problems/lfu-cache/", difficulty: "Hard" },
  { day: 99, topic: "Design", name: "Design Twitter", link: "https://leetcode.com/problems/design-twitter/", difficulty: "Medium" },
  { day: 100, topic: "Design", name: "Implement Stack using Queues", link: "https://leetcode.com/problems/implement-stack-using-queues/", difficulty: "Easy" },
  { day: 100, topic: "Design", name: "Design Circular Queue", link: "https://leetcode.com/problems/design-circular-queue/", difficulty: "Medium" },
  { day: 100, topic: "Design", name: "Serialize and Deserialize Binary Tree", link: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/", difficulty: "Hard" },
  { day: 101, topic: "Design", name: "Design Hit Counter", link: "https://leetcode.com/problems/design-hit-counter/", difficulty: "Medium" },
  { day: 101, topic: "Design", name: "Design Underground System", link: "https://leetcode.com/problems/design-underground-system/", difficulty: "Medium" },
  { day: 101, topic: "Design", name: "Design Browser History", link: "https://leetcode.com/problems/design-browser-history/", difficulty: "Medium" },
  { day: 102, topic: "Intervals", name: "Merge Intervals", link: "https://leetcode.com/problems/merge-intervals/", difficulty: "Medium" },
  { day: 102, topic: "Intervals", name: "Insert Interval", link: "https://leetcode.com/problems/insert-interval/", difficulty: "Medium" },
  { day: 102, topic: "Intervals", name: "Interval List Intersections", link: "https://leetcode.com/problems/interval-list-intersections/", difficulty: "Medium" },
  { day: 103, topic: "Intervals", name: "Meeting Rooms", link: "https://leetcode.com/problems/meeting-rooms/", difficulty: "Easy" },
  { day: 103, topic: "Intervals", name: "Minimum Number of Arrows", link: "https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/", difficulty: "Medium" },
  { day: 103, topic: "Intervals", name: "My Calendar I", link: "https://leetcode.com/problems/my-calendar-i/", difficulty: "Medium" },
  { day: 104, topic: "Monotonic Stack", name: "Next Greater Element II", link: "https://leetcode.com/problems/next-greater-element-ii/", difficulty: "Medium" },
  { day: 104, topic: "Monotonic Stack", name: "Largest Rectangle in Histogram", link: "https://leetcode.com/problems/largest-rectangle-in-histogram/", difficulty: "Hard" },
  { day: 104, topic: "Monotonic Stack", name: "Maximal Rectangle", link: "https://leetcode.com/problems/maximal-rectangle/", difficulty: "Hard" },

  // Day 105-110: Mixed Review / Contest Problems
  { day: 105, topic: "Union Find", name: "Number of Provinces", link: "https://leetcode.com/problems/number-of-provinces/", difficulty: "Medium" },
  { day: 105, topic: "Union Find", name: "Redundant Connection", link: "https://leetcode.com/problems/redundant-connection/", difficulty: "Medium" },
  { day: 105, topic: "Union Find", name: "Most Stones Removed with Same Row or Column", link: "https://leetcode.com/problems/most-stones-removed-with-same-row-or-column/", difficulty: "Medium" },
  { day: 106, topic: "Union Find", name: "Accounts Merge", link: "https://leetcode.com/problems/accounts-merge/", difficulty: "Medium" },
  { day: 106, topic: "Union Find", name: "Longest Consecutive Sequence", link: "https://leetcode.com/problems/longest-consecutive-sequence/", difficulty: "Medium" },
  { day: 106, topic: "Union Find", name: "Making A Large Island", link: "https://leetcode.com/problems/making-a-large-island/", difficulty: "Hard" },
  { day: 107, topic: "Segment Tree", name: "Range Sum Query - Mutable", link: "https://leetcode.com/problems/range-sum-query-mutable/", difficulty: "Medium" },
  { day: 107, topic: "Segment Tree", name: "Count of Smaller Numbers After Self", link: "https://leetcode.com/problems/count-of-smaller-numbers-after-self/", difficulty: "Hard" },
  { day: 107, topic: "Segment Tree", name: "My Calendar II", link: "https://leetcode.com/problems/my-calendar-ii/", difficulty: "Medium" },
  { day: 108, topic: "Mixed Review", name: "Median of Two Sorted Arrays", link: "https://leetcode.com/problems/median-of-two-sorted-arrays/", difficulty: "Hard" },
  { day: 108, topic: "Mixed Review", name: "Merge k Sorted Lists", link: "https://leetcode.com/problems/merge-k-sorted-lists/", difficulty: "Hard" },
  { day: 108, topic: "Mixed Review", name: "Trapping Rain Water", link: "https://leetcode.com/problems/trapping-rain-water/", difficulty: "Hard" },
  { day: 109, topic: "Mixed Review", name: "Alien Dictionary", link: "https://leetcode.com/problems/alien-dictionary/", difficulty: "Hard" },
  { day: 109, topic: "Mixed Review", name: "Serialize and Deserialize Binary Tree", link: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/", difficulty: "Hard" },
  { day: 109, topic: "Mixed Review", name: "Word Ladder II", link: "https://leetcode.com/problems/word-ladder-ii/", difficulty: "Hard" },
  { day: 110, topic: "Mixed Review", name: "N-Queens", link: "https://leetcode.com/problems/n-queens/", difficulty: "Hard" },
  { day: 110, topic: "Mixed Review", name: "Regular Expression Matching", link: "https://leetcode.com/problems/regular-expression-matching/", difficulty: "Hard" },
  { day: 110, topic: "Mixed Review", name: "Longest Valid Parentheses", link: "https://leetcode.com/problems/longest-valid-parentheses/", difficulty: "Hard" },
];
